In [2]:
import sqlite3
import pandas as pd

In [3]:
df = pd.read_csv('chat_messages.csv')
df

,text,handle_id,date,message_date,timestamp,month,year,is_sent,message_id,phone_number,chat_id
0,Not bothersome at all there’s nothing interest...,1.0,2019-09-06,5.895196e+17,2019-09-06 23:26:57,9.0,2019.0,1.0,1.0,+19142551372,1.0
1,lol,1.0,2019-09-06,5.895196e+17,2019-09-06 23:27:13,9.0,2019.0,0.0,2.0,+19142551372,1.0
2,And I also care about u,1.0,2019-09-06,5.895196e+17,2019-09-06 23:27:13,9.0,2019.0,1.0,3.0,+19142551372,1.0
3,NaN,1.0,2019-09-06,5.895196e+17,2019-09-06 23:27:16,9.0,2019.0,0.0,4.0,+19142551372,1.0
4,oops,1.0,2019-09-06,5.895196e+17,2019-09-06 23:27:18,9.0,2019.0,0.0,5.0,+19142551372,1.0
...,...,...,...,...,...,...,...,...,...,...,...
373711,Liked “4:30?”,300.0,2023-05-05,7.050043e+17,2023-05-05 14:31:55,5.0,2023.0,0.0,373973.0,+13057991141,326.0
373712,Liked “4:30?”,293.0,2023-05-05,7.050043e+17,2023-05-05 14:32:03,5.0,2023.0,0.0,373974.0,+19146469727,326.0
373713,What about 5:30,293.0,2023-05-05,7.050064e+17,2023-05-05 15:06:23,5.0,2023.0,0.0,373975.0,+19146469727,326.0
373714,Loved “What about 5:30”,299.0,2023-05-05,7.050064e+17,2023-05-05 15:06:41,5.0,2023.0,0.0,373976.0,+19012297145,326.0
373715,Omw to practice and packed clothes for after,493.0,2023-05-05,7.050065e+17,2023-05-05 15:07:46,5.0,2023.0,0.0,373977.0,+14076163499,646.0